# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to Linux

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install NPM dependencies and build native binary
      run: yarn
    - name: Package native binary and upload to github
      run: npm run upload-binary
      env:
        NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: remove native/index.node before publishing
      run: rm native/index.node
    - name: Publish to NPM
      run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc && npm publish --access=public
      if: ${{ matrix.node-version == '12.x' }}
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
