# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish binary to macOS

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: setup rustfmt
      run: rustup component add rustfmt --toolchain stable-x86_64-apple-darwin
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install NPM dependencies and build native binary
      run: yarn
    - name: remove native built artifact before publishing
      run: npm run clear-artifact
    - name: Package native binary and upload to github
      run: npm run upload-binary
      env:
        NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
